name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Congratulations on raising your first issue! We thank you for your contribution and welcome you onboard. Please do not hesitate to reach out to the admins for any assistance.'
        pr-message: 'Congratulations on submitting your first pull request! We thank you for your contribution and welcome you onboard. Please do not hesitate to reach out to the admins for any assistance.'

